//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteSecretary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meetings
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ClientID { get; set; }
        public string date { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
